"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'subaruu'? I predict False.");
console.log(car == 'subaruu');
console.log("Is car == 'Subaru'? I predict False.");
console.log(car == 'Subaru');
let animal = 'Lion';
console.log("Is animal == 'Lion'? I predict True.");
console.log(animal == 'Lion');
console.log("Is animal == 'lion'? I predict False.");
console.log(animal == 'lion');
console.log("Is animal == 'Cheetah'? I predict False.");
console.log(animal == 'Cheetah');
let captain = 'Babar Azam';
console.log("Is captain == 'Babar Azam'? I predict True.");
console.log(captain == 'Babar Azam');
console.log("Is captain == 'Sheikh Farhan'? I predict False.");
console.log(captain == 'Sheikh Farhan');
let asiaCupIn = 'Pakistan';
console.log("Is asiaCupIn == 'Pakistan'? I predict True.");
console.log(asiaCupIn == 'Pakistan');
console.log("Is asiaCupIn == 'India'? I predict False.");
console.log(asiaCupIn == 'India');
